{{- $root := . -}}
{{- range $name, $comp := ( .Values.components | default dict ) }}
{{- if and $comp.service $comp.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "inres.componentFullname" (dict "root" $root "name" $name) }}
  labels:
    {{- include "inres.componentLabels" (dict "root" $root "name" $name) | nindent 4 }}
spec:
  type: {{ default "ClusterIP" $comp.service.type }}
  {{- if $comp.service.ports }}
  ports:
    {{- range $comp.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  {{- else }}
  ports:
    - port: {{ $comp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- end }}
  selector:
    {{- include "inres.componentSelectorLabels" (dict "root" $root "name" $name) | nindent 4 }}
---
{{- end }}
{{- end }}
